all: gpp clang

gpp: 
	@echo "Compiling using g++"
	@echo -n 'Command: '
	g++ -o myprogramgpp main.cpp


clang: 
	@echo "Compiling using clang"
	@echo -n 'Command: '
	clang++ -o myprogramclang main.cpp



.PHONY clean:
	@rm -f myprogram*
